swagger: '2.0'
info:
  title: EPS API
  description: |
    The **eps-api** is responsible for eps data. The service provides endpoints for
    retrieving battery, solar panels and eps_subsystems data by the following criteria:
      * panel / subsystem
      * state
      * time window
  version: "1.0.0"

# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /eps
produces:
  - application/json
paths:
  /battery:
    post:
      summary: Create battery log
      parameters:
        - name: batteryLog
          in: body
          required: true
          schema:
            $ref: '#/definitions/BatteryLog'
      tags:
        - Battery
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: Battery log has been created
          schema:
            $ref: '#/definitions/BatteryLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'

    get:
      summary: Query battery log
      description: |
        Query battery logs by their properties
      parameters:
        - name: state
          in: query
          type: string
          enum:
            - CHARGING
            - DISCHARGING
          default: CHARGING
          required: false
        - name: since
          in: query
          type: string
          format: date-time
          required: false
        - name: until
          in: query
          type: string
          format: date-time
          required: false
        - name: pageSize
          in: query
          type: integer
          required: false
          default: 50
          description: |
            The results will be provided in chunks. This parameters represents the chunk size
        - name: pageIndex
          in: query
          type: integer
          required: false
          default: 1
      tags:
        - Battery
      produces:
        - application/json
      responses:
        200:
          description: |
            A list of battery logs which fulfill the requirements
          schema:
            type: array
            items:
                $ref: '#/definitions/BatteryLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'

  /battery/{registrationId}:
    get:
      summary: Single battery log
      description: Retrieve a battery log by id
      parameters:
        - name: registrationId
          in: path
          type: string
          description: Battery log identifier
          required: true
      tags:
        - Battery
      produces:
        - application/json
      responses:
        200:
          description: Battery log
          schema:
            $ref: '#/definitions/BatteryLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not found
          schema:
            type: string
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'

  /panels:
    post:
      summary: Create panel log
      parameters:
        - name: panelLog
          in: body
          required: true
          schema:
            $ref: '#/definitions/PanelLog'
      tags:
        - Panels
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: Panel log has been created
          schema:
            $ref: '#/definitions/PanelLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'

    get:
      summary: Query panel logs
      description: |
        Query panel logs by their properties
      parameters:
        - name: panelId
          in: query
          type: integer
          format: int32
          description: panel id
          required: false
        - name: state
          in: query
          type: string
          enum:
            - NORMAL
            - WARNING
          default: NORMAL
          required: false
        - name: since
          in: query
          type: string
          format: date-time
          required: false
        - name: until
          in: query
          type: string
          format: date-time
          required: false
        - name: pageSize
          in: query
          type: integer
          required: false
          default: 50
          description: |
            The results will be provided in chunks. This parameters represents the chunk size
        - name: pageIndex
          in: query
          type: integer
          required: false
          default: 1
      tags:
        - Panels
      produces:
        - application/json
      responses:
        200:
          description: Panels
          schema:
            type: array
            items:
                $ref: '#/definitions/PanelLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'
  
  /panels/{registrationId}:
    get:
      summary: Single panel log
      description: Retrieve a panel log by id
      parameters:
        - name: registrationId
          in: path
          type: string
          description: Battery log identifier
          required: true
      tags:
        - Panels
      produces:
        - application/json
      responses:
        200:
          description: Panel log
          schema:
            $ref: '#/definitions/PanelLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not found
          schema:
            type: string
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'
            
  /subsystems:
    post:
      summary: Create subsystem log
      parameters:
        - name: SubsystemLog
          in: body
          required: true
          schema:
            $ref: '#/definitions/SubsystemLog'
      tags:
        - Subsystems
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: Subsystem log has been created
          schema:
            $ref: '#/definitions/SubsystemLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'

    get:
      summary: Query subsystem log
      description: |
        Query battery logs by their properties
      parameters:
        - name: subsystemId
          in: query
          type: integer
          format: int32
        - name: state
          in: query
          type: string
          enum:
            - ON
            - OFF
          default: ON
          required: false
        - name: expectedState
          in: query
          type: string
          enum:
            - ON
            - OFF
          default: ON
          required: false
        - name: since
          in: query
          type: string
          format: date-time
          required: false
        - name: until
          in: query
          type: string
          format: date-time
          required: false
        - name: pageSize
          in: query
          type: integer
          required: false
          default: 50
          description: |
            The results will be provided in chunks. This parameters represents the chunk size
        - name: pageIndex
          in: query
          type: integer
          required: false
          default: 1
      tags:
        - Subsystems
      produces:
        - application/json
      responses:
        200:
          description: |
            A list of subsystem logs which fulfill the requirements
          schema:
            type: array
            items:
                $ref: '#/definitions/SubsystemLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'

  /subsystems/{registrationId}:
    get:
      summary: Single subsystem log
      description: Retrieve a subsystem log by id
      parameters:
        - name: registrationId
          in: path
          type: string
          description: Subsystem log identifier
          required: true
      tags:
        - Subsystems
      produces:
        - application/json
      responses:
        200:
          description: Subsystem log
          schema:
            $ref: '#/definitions/SubsystemLog'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not found
          schema:
            type: string
        500:
          description: Service error
          schema:
            $ref: '#/definitions/Error'
definitions:
  BatteryLog:
    type: object
    properties:
      registrationId:
        type: integer
        format: int64
      state:
        type: string
        enum:
          - CHARGING
          - DISCHARGING
      level:
        type: integer
        format: int32
      createdOn:
        type: string
        format: date-time
  
  PanelLog:
    type: object
    properties:
      registrationId:
        type: integer
        format: int64
      panelId:
        type: integer
        format: int32
      state:
        type: string
        enum:
          - NORMAL
          - WARNING
      current:
        type: number
        format: double
      voltage:
        type: number
        format: double
      createdOn:
        type: string
        format: date-time
        
  SubsystemLog:
    type: object
    properties:
      registrationId:
        type: integer
        format: int64
      subsystemId:
        type: integer
        format: int32
      state:
        type: string
        enum:
          - ON
          - OFF
      expectedState:
        type: string
        enum:
          - ON
          - OFF
      current:
        type: number
        format: double
      voltage:
        type: number
        format: double
      createdOn:
        type: string
        format: date-time

  Error:
    type: object
    properties:
      message:
        type: string